sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn test
