language: node_js
node_js: node
env:
  - TYPESCRIPT_VERSION=rc
  - TYPESCRIPT_VERSION=3.7
  - TYPESCRIPT_VERSION=3.6
  - TYPESCRIPT_VERSION=3.5
install:
  - cd npm-package
  - yarn --ignore-scripts
  - yarn add typescript@$TYPESCRIPT_VERSION
script: yarn prepare
